version: "3.8"

networks:
  reverse_proxy:
    external: true

services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./tls:/etc/tls"
    restart: always
    networks:
      - reverse_proxy 
